export const PLATFORM_PERMISSIONS = [
  "users:create",
  "users:edit",
  "users:delete",
  "teams:create",
  "teams:edit",
  "teams:delete",
  "groups:create",
  "groups:edit",
  "groups:delete",
  "roles:create",
  "roles:edit",
  "roles:delete",
  "admin:grant",
];

export const NOTE_PERMISSIONS = [
  "notes:create",
  "notes:edit_own",
  "notes:edit_shared",
  "notes:delete_own",
  "notes:delete_shared",
  "notes:view_private",
  "notes:view_shared",
  "notes:share_team",
  "notes:share_users",
  "notes:download",
  "notes:upload_attachments",
  "notes:delete_attachments",
];

export const CALENDAR_PERMISSIONS = [
  "calendar:create",
  "calendar:edit_own",
  "calendar:edit_others",
  "calendar:delete_own",
  "calendar:delete_others",
  "calendar:view_team",
  "calendar:assign_users",
  "calendar:assign_teams",
];

export const TASK_PERMISSIONS = [
  "tasks:create",
  "tasks:edit_own",
  "tasks:edit_others",
  "tasks:delete_own",
  "tasks:delete_others",
  "tasks:move_columns",
  "tasks:reassign_users",
  "tasks:reassign_teams",
  "tasks:move_groups",
  "tasks:view_team",
  "tasks:view_group",
];

export const AUDIT_PERMISSIONS = [
  "audit:view_team",
  "audit:view_group",
  "audit:view_all",
];

export const ALL_PERMISSIONS = [
  ...PLATFORM_PERMISSIONS,
  ...NOTE_PERMISSIONS,
  ...CALENDAR_PERMISSIONS,
  ...TASK_PERMISSIONS,
  ...AUDIT_PERMISSIONS,
];

export const PERMISSION_DESCRIPTIONS: Record<string, string> = {
  "users:create": "Add new users to the platform",
  "users:edit": "Update user profiles and settings",
  "users:delete": "Remove users permanently",
  "teams:create": "Create new teams",
  "teams:edit": "Rename or update team details",
  "teams:delete": "Delete teams and all their data",
  "groups:create": "Create groups within a team",
  "groups:edit": "Rename or update groups",
  "groups:delete": "Delete groups",
  "roles:create": "Create custom roles",
  "roles:edit": "Modify role permissions",
  "roles:delete": "Delete custom roles",
  "admin:grant": "Promote users to platform admin",
  "audit:view_all": "View audit logs across all teams",
  "notes:create": "Write new notes",
  "notes:edit_own": "Edit notes you created",
  "notes:edit_shared": "Edit notes shared with you",
  "notes:delete_own": "Delete your own notes",
  "notes:delete_shared": "Delete shared notes",
  "notes:view_private": "Access private notes",
  "notes:view_shared": "Read notes shared with your team",
  "notes:share_team": "Share notes with the whole team",
  "notes:share_users": "Share notes with specific users",
  "notes:download": "Export notes as .md files",
  "notes:upload_attachments": "Attach files to notes",
  "notes:delete_attachments": "Remove attachments from notes",
  "calendar:create": "Add calendar events",
  "calendar:edit_own": "Edit your own events",
  "calendar:edit_others": "Edit anyone's events",
  "calendar:delete_own": "Delete your events",
  "calendar:delete_others": "Delete any event",
  "calendar:view_team": "See the team calendar",
  "calendar:assign_users": "Assign events to users",
  "calendar:assign_teams": "Assign events to teams",
  "tasks:create": "Create new tasks",
  "tasks:edit_own": "Edit tasks you created",
  "tasks:edit_others": "Edit any task",
  "tasks:delete_own": "Delete your tasks",
  "tasks:delete_others": "Delete any task",
  "tasks:move_columns": "Move tasks between columns",
  "tasks:reassign_users": "Reassign tasks to other users",
  "tasks:reassign_teams": "Reassign tasks to other teams",
  "tasks:move_groups": "Move tasks between groups",
  "tasks:view_team": "View tasks in your team",
  "tasks:view_group": "View tasks in your group",
  "audit:view_team": "View audit logs for your team",
  "audit:view_group": "View audit logs for your group",
};
